import type { Template } from '../types'

/**
 * Case drills, singular and plural.
 *
 * Distractors always come from the answer word's OWN paradigm, so the learner
 * has to decide a case rather than recognise a word.
 */
export const CASE_TEMPLATES: Template[] = [
  // ── Genitiv Singular ─────────────────────────────────────
  {
    id: 'gen.sg.do',
    conceptIds: ['case.gen.sg'],
    kind: 'cloze',
    frame: 'Idę do {n1}.',
    promptDe: 'Ich gehe zu/nach …',
    slots: { n1: { pos: 'N', tag: 'sg.gen', semantic: 'place' } },
    answerSlot: 'n1',
    distractors: { fromTags: ['sg.nom', 'sg.acc', 'sg.ins', 'sg.loc'], count: 3 },
    hintDe: 'do verlangt immer den Genitiv.',
  },
  {
    id: 'gen.sg.bez',
    conceptIds: ['case.gen.sg'],
    kind: 'cloze',
    frame: 'Kawa bez {n1}.',
    promptDe: 'Kaffee ohne …',
    slots: { n1: { pos: 'N', tag: 'sg.gen', semantic: 'concrete' } },
    answerSlot: 'n1',
    distractors: { fromTags: ['sg.nom', 'sg.acc', 'sg.dat'], count: 3 },
    hintDe: 'bez („ohne") verlangt den Genitiv.',
  },
  {
    id: 'gen.sg.transform',
    conceptIds: ['case.gen.sg'],
    kind: 'transform',
    frame: '{n1}',
    promptDe: 'Setze das Wort in den Genitiv Singular.',
    slots: { n1: { pos: 'N', tag: 'sg.gen' } },
    answerSlot: 'n1',
    hintDe: 'Männlich/sächlich → -a oder -u. Weiblich → -y oder -i.',
  },
  {
    id: 'gen.negation.mam',
    conceptIds: ['case.gen.negation'],
    kind: 'cloze',
    frame: 'Nie mam {n1}.',
    promptDe: 'Ich habe kein/keine …',
    slots: { n1: { pos: 'N', tag: 'sg.gen', semantic: 'concrete' } },
    answerSlot: 'n1',
    distractors: { fromTags: ['sg.acc', 'sg.nom', 'sg.ins'], count: 3 },
    hintDe: 'Verneinung verwandelt das Akkusativobjekt in einen Genitiv.',
  },
  {
    id: 'gen.negation.widze',
    conceptIds: ['case.gen.negation'],
    kind: 'cloze',
    frame: 'Nie widzę {n1}.',
    promptDe: 'Ich sehe … nicht',
    slots: { n1: { pos: 'N', tag: 'sg.gen', semantic: 'person' } },
    answerSlot: 'n1',
    distractors: { fromTags: ['sg.nom', 'sg.ins', 'sg.dat'], count: 3 },
    hintDe: 'Auch hier: nie + Verb → Genitiv.',
  },

  // ── Lokativ Singular ─────────────────────────────────────
  {
    id: 'loc.sg.w',
    conceptIds: ['case.loc.sg'],
    kind: 'cloze',
    frame: 'Jestem w {n1}.',
    promptDe: 'Ich bin in …',
    slots: { n1: { pos: 'N', tag: 'sg.loc', semantic: 'place' } },
    answerSlot: 'n1',
    distractors: { fromTags: ['sg.nom', 'sg.gen', 'sg.acc', 'sg.ins'], count: 3 },
    hintDe: 'w („in", Ort) verlangt den Lokativ.',
  },
  {
    id: 'loc.sg.o',
    conceptIds: ['case.loc.sg'],
    kind: 'cloze',
    frame: 'Mówimy o {n1}.',
    promptDe: 'Wir sprechen über …',
    slots: { n1: { pos: 'N', tag: 'sg.loc', semantic: 'concrete' } },
    answerSlot: 'n1',
    distractors: { fromTags: ['sg.nom', 'sg.gen', 'sg.ins'], count: 3 },
    hintDe: 'o („über", Thema) verlangt den Lokativ.',
  },
  {
    id: 'loc.sg.transform',
    conceptIds: ['case.loc.sg'],
    kind: 'transform',
    frame: '{n1}',
    promptDe: 'Setze das Wort in den Lokativ Singular.',
    slots: { n1: { pos: 'N', tag: 'sg.loc' } },
    answerSlot: 'n1',
    hintDe: 'Achte auf Konsonantenwechsel: miasto → mieście.',
  },

  // ── Dativ Singular ───────────────────────────────────────
  {
    id: 'dat.sg.daje',
    conceptIds: ['case.dat.sg'],
    kind: 'cloze',
    frame: 'Daję {n1} książkę.',
    promptDe: 'Ich gebe … ein Buch',
    slots: { n1: { pos: 'N', tag: 'sg.dat', semantic: 'person' } },
    answerSlot: 'n1',
    distractors: { fromTags: ['sg.nom', 'sg.acc', 'sg.gen', 'sg.ins'], count: 3 },
    hintDe: 'Der Empfänger steht im Dativ — wie im Deutschen.',
  },
  {
    id: 'dat.sg.pomagam',
    conceptIds: ['case.dat.sg'],
    kind: 'cloze',
    frame: 'Pomagam {n1}.',
    promptDe: 'Ich helfe …',
    slots: { n1: { pos: 'N', tag: 'sg.dat', semantic: 'person' } },
    answerSlot: 'n1',
    distractors: { fromTags: ['sg.acc', 'sg.gen', 'sg.nom'], count: 3 },
    hintDe: 'pomagać verlangt den Dativ — genau wie „helfen".',
  },

  // ── Plural ───────────────────────────────────────────────
  {
    id: 'nom.pl.transform',
    conceptIds: ['case.nom.pl'],
    kind: 'transform',
    frame: '{n1}',
    promptDe: 'Setze das Wort in den Nominativ Plural.',
    slots: { n1: { pos: 'N', tag: 'pl.nom' } },
    answerSlot: 'n1',
    hintDe: 'Männlich-personal → -i/-y/-owie. Alles andere → -y/-i/-e.',
  },
  {
    id: 'nom.pl.sa',
    conceptIds: ['case.nom.pl'],
    kind: 'cloze',
    frame: 'To są {n1}.',
    promptDe: 'Das sind …',
    slots: { n1: { pos: 'N', tag: 'pl.nom', semantic: 'concrete' } },
    answerSlot: 'n1',
    distractors: { fromTags: ['sg.nom', 'pl.gen', 'pl.acc', 'pl.ins'], count: 3 },
    hintDe: 'Nach to są steht der Nominativ Plural.',
  },
  {
    id: 'acc.pl.widze',
    conceptIds: ['case.acc.pl'],
    kind: 'cloze',
    frame: 'Widzę {n1}.',
    promptDe: 'Ich sehe … (Mehrzahl)',
    slots: { n1: { pos: 'N', tag: 'pl.acc', semantic: 'concrete' } },
    answerSlot: 'n1',
    distractors: { fromTags: ['pl.gen', 'pl.ins', 'pl.loc', 'sg.acc'], count: 3 },
    hintDe: 'Außer bei Männergruppen ist der Akkusativ Plural gleich dem Nominativ Plural.',
  },
  {
    id: 'gen.pl.transform',
    conceptIds: ['case.gen.pl'],
    kind: 'transform',
    frame: '{n1}',
    promptDe: 'Setze das Wort in den Genitiv Plural.',
    slots: { n1: { pos: 'N', tag: 'pl.gen' } },
    answerSlot: 'n1',
    hintDe: 'Weiblich/sächlich verlieren den Endvokal. Männlich bekommt -ów.',
  },
  {
    id: 'gen.pl.duzo',
    conceptIds: ['case.gen.pl'],
    kind: 'cloze',
    frame: 'Dużo {n1}.',
    promptDe: 'Viele/viel …',
    slots: { n1: { pos: 'N', tag: 'pl.gen', semantic: 'concrete' } },
    answerSlot: 'n1',
    distractors: { fromTags: ['pl.nom', 'pl.acc', 'pl.ins'], count: 3 },
    hintDe: 'Mengenangaben wie dużo verlangen den Genitiv Plural.',
  },
  {
    id: 'ins.pl.z',
    conceptIds: ['case.ins.pl'],
    kind: 'cloze',
    frame: 'Idę z {n1}.',
    promptDe: 'Ich gehe mit … (Mehrzahl)',
    slots: { n1: { pos: 'N', tag: 'pl.ins', semantic: 'companion' } },
    answerSlot: 'n1',
    distractors: { fromTags: ['pl.nom', 'pl.gen', 'pl.loc', 'pl.dat'], count: 3 },
    hintDe: 'Instrumental Plural ist fast immer -ami.',
  },
  {
    id: 'ins.pl.transform',
    conceptIds: ['case.ins.pl'],
    kind: 'transform',
    frame: '{n1}',
    promptDe: 'Setze das Wort in den Instrumental Plural.',
    slots: { n1: { pos: 'N', tag: 'pl.ins' } },
    answerSlot: 'n1',
    hintDe: 'Eine Endung für alle Geschlechter: -ami.',
  },
  {
    id: 'loc.pl.w',
    conceptIds: ['case.loc.pl'],
    kind: 'cloze',
    frame: 'Mieszkam w {n1}.',
    promptDe: 'Ich wohne in … (Mehrzahl)',
    slots: { n1: { pos: 'N', tag: 'pl.loc', semantic: 'place' } },
    answerSlot: 'n1',
    distractors: { fromTags: ['pl.nom', 'pl.gen', 'pl.ins', 'pl.dat'], count: 3 },
    hintDe: 'Lokativ Plural ist immer -ach.',
  },
  {
    id: 'loc.pl.transform',
    conceptIds: ['case.loc.pl'],
    kind: 'transform',
    frame: '{n1}',
    promptDe: 'Setze das Wort in den Lokativ Plural.',
    slots: { n1: { pos: 'N', tag: 'pl.loc' } },
    answerSlot: 'n1',
    hintDe: 'Keine Konsonantenwechsel im Plural — einfach -ach.',
  },
  {
    id: 'dat.pl.daje',
    conceptIds: ['case.dat.pl'],
    kind: 'cloze',
    frame: 'Daję prezenty {n1}.',
    promptDe: 'Ich gebe … Geschenke (Mehrzahl)',
    slots: { n1: { pos: 'N', tag: 'pl.dat', semantic: 'person' } },
    answerSlot: 'n1',
    distractors: { fromTags: ['pl.nom', 'pl.gen', 'pl.ins', 'pl.loc'], count: 3 },
    hintDe: 'Dativ Plural ist immer -om.',
  },
  {
    id: 'dat.pl.transform',
    conceptIds: ['case.dat.pl'],
    kind: 'transform',
    frame: '{n1}',
    promptDe: 'Setze das Wort in den Dativ Plural.',
    slots: { n1: { pos: 'N', tag: 'pl.dat' } },
    answerSlot: 'n1',
    hintDe: 'DatOM — das O steckt im Namen.',
  },

  // ── Vokativ ──────────────────────────────────────────────
  {
    id: 'voc.quiz',
    conceptIds: ['case.voc'],
    kind: 'quiz',
    frame: '',
    promptDe: '',
    slots: {},
    answerSlot: '',
    hintDe: 'Weibliche Namen auf -a → -o/-u. Männliche → -e/-u.',
    items: [
      { promptDe: 'Wie rufst du Anna?', text: 'Anna', answer: 'Aniu!', wrong: ['Anna!', 'Anny!', 'Annie!'] },
      { promptDe: 'Wie sprichst du deine Mutter an?', text: 'mama', answer: 'mamo!', wrong: ['mama!', 'mamy!', 'mamie!'] },
      { promptDe: 'Höfliche Anrede an einen Arzt?', text: 'pan doktor', answer: 'panie doktorze!', wrong: ['pan doktor!', 'pana doktora!', 'panu doktorowi!'] },
      { promptDe: 'Wie rufst du deinen Freund Marek?', text: 'Marek', answer: 'Marku!', wrong: ['Marek!', 'Marka!', 'Markiem!'] },
      { promptDe: 'Welcher Fall ist die Anrede?', text: '„Aniu!"', answer: 'Vokativ', wrong: ['Nominativ', 'Dativ', 'Lokativ'] },
    ],
  },
]
