import type { Template } from '../types'

/** Gender, adjectives, prepositions, numerals, pronouns and syntax. */
export const MISC_TEMPLATES: Template[] = [
  {
    id: 'gender.animacy.quiz',
    conceptIds: ['gender.masc.animacy'],
    kind: 'quiz',
    frame: '', promptDe: '', slots: {}, answerSlot: '',
    hintDe: 'Mensch → personal. Tier → belebt. Ding → unbelebt.',
    items: [
      { promptDe: 'Welche Klasse ist „student"?', text: 'student', answer: 'männlich-personal', wrong: ['männlich belebt', 'männlich unbelebt', 'weiblich'] },
      { promptDe: 'Welche Klasse ist „kot"?', text: 'kot', answer: 'männlich belebt', wrong: ['männlich-personal', 'männlich unbelebt', 'sächlich'] },
      { promptDe: 'Welche Klasse ist „stół"?', text: 'stół', answer: 'männlich unbelebt', wrong: ['männlich belebt', 'männlich-personal', 'sächlich'] },
      { promptDe: 'Akkusativ von „kot"?', text: 'Widzę …', answer: 'kota', wrong: ['kot', 'kotem', 'kotu'] },
      { promptDe: 'Akkusativ von „stół"?', text: 'Widzę …', answer: 'stół', wrong: ['stołu', 'stołem', 'stole'] },
      { promptDe: 'Nominativ Plural von „student"?', text: 'student →', answer: 'studenci', wrong: ['studenty', 'studentów', 'studentami'] },
    ],
  },

  // ── Adjektive ────────────────────────────────────────────
  {
    id: 'adj.sg.nom',
    conceptIds: ['adj.agreement.sg'],
    kind: 'cloze',
    frame: '{a1} dom',
    promptDe: 'Setze das Adjektiv passend zu „dom" (männlich).',
    slots: { a1: { pos: 'A', tag: 'sg.m.nom' } },
    answerSlot: 'a1',
    distractors: { fromTags: ['sg.f.nom', 'sg.n.nom', 'pl.nom'], count: 3 },
    hintDe: 'Männlich Nominativ Singular endet auf -y oder -i.',
  },
  {
    id: 'adj.sg.f.acc',
    conceptIds: ['adj.agreement.sg'],
    kind: 'cloze',
    frame: 'Widzę {a1} kobietę.',
    promptDe: 'Ich sehe die … Frau (Akkusativ, weiblich)',
    slots: { a1: { pos: 'A', tag: 'sg.f.acc' } },
    answerSlot: 'a1',
    distractors: { fromTags: ['sg.f.nom', 'sg.m.nom', 'sg.f.gen'], count: 3 },
    hintDe: 'Das Adjektiv macht Fall UND Geschlecht mit: -ą im Akkusativ weiblich.',
  },
  {
    id: 'adj.pl.nom',
    conceptIds: ['adj.agreement.pl'],
    kind: 'cloze',
    frame: '{a1} książki',
    promptDe: 'Setze das Adjektiv passend zu „książki" (Plural, nicht-personal).',
    slots: { a1: { pos: 'A', tag: 'pl.nom' } },
    answerSlot: 'a1',
    distractors: { fromTags: ['pl.m.hum.nom', 'sg.f.nom', 'sg.m.nom'], count: 3 },
    hintDe: 'Alles außer Männergruppen bekommt -e.',
  },
  {
    id: 'adj.pl.hum',
    conceptIds: ['adj.agreement.pl'],
    kind: 'cloze',
    frame: '{a1} studenci',
    promptDe: 'Setze das Adjektiv passend zu „studenci" (Männergruppe).',
    slots: { a1: { pos: 'A', tag: 'pl.m.hum.nom' } },
    answerSlot: 'a1',
    distractors: { fromTags: ['pl.nom', 'sg.m.nom', 'pl.gen'], count: 3 },
    hintDe: 'Männlich-personal bekommt -i/-y, oft mit Konsonantenwechsel.',
  },
  {
    id: 'adj.comparative.quiz',
    conceptIds: ['adj.comparative'],
    kind: 'quiz',
    frame: '', promptDe: '', slots: {}, answerSlot: '',
    hintDe: 'Komparativ -szy/-ejszy, Superlativ naj-.',
    items: [
      { promptDe: 'Komparativ von „duży" (groß)', text: 'duży →', answer: 'większy', wrong: ['dużejszy', 'najduży', 'dużyszy'] },
      { promptDe: 'Komparativ von „dobry" (gut)', text: 'dobry →', answer: 'lepszy', wrong: ['dobrzejszy', 'najdobry', 'dobrszy'] },
      { promptDe: 'Superlativ von „dobry"', text: 'dobry →', answer: 'najlepszy', wrong: ['najdobry', 'lepszy', 'bardziej dobry'] },
      { promptDe: 'Komparativ von „zły" (schlecht)', text: 'zły →', answer: 'gorszy', wrong: ['złejszy', 'najzły', 'bardziej zły'] },
      { promptDe: 'Komparativ von „mały" (klein)', text: 'mały →', answer: 'mniejszy', wrong: ['małszy', 'najmały', 'małejszy'] },
    ],
  },

  // ── Präpositionen ────────────────────────────────────────
  {
    id: 'prep.gen.match',
    conceptIds: ['prep.gen'],
    kind: 'match',
    frame: '', promptDe: '', slots: {}, answerSlot: '',
    hintDe: 'do, od, bez, dla, u — alle Genitiv.',
  },
  {
    id: 'prep.gen.quiz',
    conceptIds: ['prep.gen'],
    kind: 'quiz',
    frame: '', promptDe: '', slots: {}, answerSlot: '',
    items: [
      { promptDe: 'Ich gehe nach Hause.', text: 'Idę do …', answer: 'domu', wrong: ['dom', 'domem', 'domie'] },
      { promptDe: 'Kaffee ohne Zucker.', text: 'Kawa bez …', answer: 'cukru', wrong: ['cukier', 'cukrem', 'cukrze'] },
      { promptDe: 'Ein Geschenk für Mama.', text: 'Prezent dla …', answer: 'mamy', wrong: ['mama', 'mamie', 'mamą'] },
      { promptDe: 'Ich bin beim Arzt.', text: 'Jestem u …', answer: 'lekarza', wrong: ['lekarz', 'lekarzem', 'lekarzu'] },
    ],
  },
  {
    id: 'prep.loc.match',
    conceptIds: ['prep.loc'],
    kind: 'match',
    frame: '', promptDe: '', slots: {}, answerSlot: '',
    hintDe: 'w, na, o, przy, po — alle Lokativ (bei Ort/Thema).',
  },
  {
    id: 'prep.motion.quiz',
    conceptIds: ['prep.motion'],
    kind: 'quiz',
    frame: '', promptDe: '', slots: {}, answerSlot: '',
    hintDe: 'Wo = Lokativ. Wohin = Akkusativ. Genau wie im Deutschen.',
    items: [
      { promptDe: 'Ich bin im Haus. (Ort)', text: 'Jestem w …', answer: 'domu (Lokativ)', wrong: ['dom (Akkusativ)', 'domem (Instrumental)', 'domu (Akkusativ)'] },
      { promptDe: 'Das Buch liegt auf dem Tisch. (Ort)', text: 'Książka jest na …', answer: 'stole (Lokativ)', wrong: ['stół (Akkusativ)', 'stołu (Genitiv)', 'stołem (Instrumental)'] },
      { promptDe: 'Ich lege das Buch auf den Tisch. (Richtung)', text: 'Kładę książkę na …', answer: 'stół (Akkusativ)', wrong: ['stole (Lokativ)', 'stołu (Genitiv)', 'stołem (Instrumental)'] },
      { promptDe: 'Welchen Fall verlangt „wo?"', text: 'gdzie?', answer: 'Lokativ', wrong: ['Akkusativ', 'Genitiv', 'Instrumental'] },
      { promptDe: 'Welchen Fall verlangt „wohin?"', text: 'dokąd?', answer: 'Akkusativ', wrong: ['Lokativ', 'Genitiv', 'Dativ'] },
    ],
  },

  // ── Zahlen ───────────────────────────────────────────────
  {
    id: 'numerals.1to4.quiz',
    conceptIds: ['numerals.1to4'],
    kind: 'quiz',
    frame: '', promptDe: '', slots: {}, answerSlot: '',
    hintDe: 'dwie nur bei weiblichen Substantiven. 2–4 nehmen den Nominativ Plural.',
    items: [
      { promptDe: 'zwei Frauen', text: '… kobiety', answer: 'dwie', wrong: ['dwa', 'dwóch', 'dwoje'] },
      { promptDe: 'zwei Häuser', text: '… domy', answer: 'dwa', wrong: ['dwie', 'dwóch', 'dwoje'] },
      { promptDe: 'drei Katzen', text: 'trzy …', answer: 'koty', wrong: ['kotów', 'kota', 'kotami'] },
      { promptDe: 'ein Haus (männlich)', text: '… dom', answer: 'jeden', wrong: ['jedna', 'jedno', 'jedni'] },
      { promptDe: 'eine Frau (weiblich)', text: '… kobieta', answer: 'jedna', wrong: ['jeden', 'jedno', 'jedni'] },
    ],
  },
  {
    id: 'numerals.5plus.quiz',
    conceptIds: ['numerals.5plus'],
    kind: 'quiz',
    frame: '', promptDe: '', slots: {}, answerSlot: '',
    hintDe: 'Ab fünf steht das Substantiv im Genitiv Plural.',
    items: [
      { promptDe: 'fünf Katzen', text: 'pięć …', answer: 'kotów', wrong: ['koty', 'kota', 'kotami'] },
      { promptDe: 'zehn Häuser', text: 'dziesięć …', answer: 'domów', wrong: ['domy', 'domu', 'domami'] },
      { promptDe: 'sieben Frauen', text: 'siedem …', answer: 'kobiet', wrong: ['kobiety', 'kobietami', 'kobiecie'] },
      { promptDe: 'Welchen Fall verlangt „pięć"?', text: 'pięć + ?', answer: 'Genitiv Plural', wrong: ['Nominativ Plural', 'Akkusativ Plural', 'Instrumental Plural'] },
      { promptDe: '22 Katzen — welche Form?', text: 'dwadzieścia dwa …', answer: 'koty', wrong: ['kotów', 'kota', 'kotami'] },
    ],
  },

  // ── Pronomen und Syntax ──────────────────────────────────
  {
    id: 'pron.personal.quiz',
    conceptIds: ['pron.personal'],
    kind: 'quiz',
    frame: '', promptDe: '', slots: {}, answerSlot: '',
    hintDe: 'Die Verbendung nennt die Person schon — das Pronomen betont nur.',
    items: [
      { promptDe: 'Gib mir das Buch. („mir")', text: 'Daj … książkę', answer: 'mi', wrong: ['mnie', 'ja', 'mną'] },
      { promptDe: 'Ich sehe dich. („dich")', text: 'Widzę …', answer: 'cię', wrong: ['ci', 'ty', 'tobą'] },
      { promptDe: 'Ich helfe ihm. („ihm")', text: 'Pomagam …', answer: 'mu', wrong: ['go', 'on', 'nim'] },
      { promptDe: 'Ich sehe sie. („sie", eine Frau)', text: 'Widzę …', answer: 'ją', wrong: ['jej', 'ona', 'nią'] },
      { promptDe: 'Warum sagt man meist nicht „ja robię"?', text: 'robię', answer: 'Die Endung nennt die Person schon', wrong: ['Es ist falsch', 'Nur schriftlich erlaubt', 'Es ist zu höflich'] },
    ],
  },
  {
    id: 'pron.possessive.quiz',
    conceptIds: ['pron.possessive'],
    kind: 'quiz',
    frame: '', promptDe: '', slots: {}, answerSlot: '',
    hintDe: 'Das Possessivum richtet sich nach dem Besitz, nicht nach dem Besitzer.',
    items: [
      { promptDe: 'mein Haus', text: '… dom', answer: 'mój', wrong: ['moja', 'moje', 'moi'] },
      { promptDe: 'meine Katze (kot ist männlich!)', text: '… kot', answer: 'mój', wrong: ['moja', 'moje', 'moi'] },
      { promptDe: 'meine Bücher', text: '… książki', answer: 'moje', wrong: ['mój', 'moja', 'moi'] },
      { promptDe: 'dein Fenster', text: '… okno', answer: 'twoje', wrong: ['twój', 'twoja', 'twoi'] },
      { promptDe: 'unser Haus', text: '… dom', answer: 'nasz', wrong: ['nasza', 'nasze', 'nasi'] },
    ],
  },
  {
    id: 'syntax.questions.quiz',
    conceptIds: ['syntax.questions'],
    kind: 'quiz',
    frame: '', promptDe: '', slots: {}, answerSlot: '',
    hintDe: 'czy stellt eine Ja/Nein-Frage, ohne die Wortstellung zu ändern.',
    items: [
      { promptDe: 'Hast du Zeit? (Ja/Nein-Frage)', text: '… masz czas?', answer: 'Czy', wrong: ['Co', 'Kto', 'Jak'] },
      { promptDe: 'Was machst du?', text: '… robisz?', answer: 'Co', wrong: ['Kto', 'Czy', 'Gdzie'] },
      { promptDe: 'Wo bist du?', text: '… jesteś?', answer: 'Gdzie', wrong: ['Kto', 'Co', 'Jak'] },
      { promptDe: 'Wer ist das?', text: '… to jest?', answer: 'Kto', wrong: ['Co', 'Czy', 'Gdzie'] },
      { promptDe: 'Warum nicht?', text: '… nie?', answer: 'Dlaczego', wrong: ['Jak', 'Gdzie', 'Kiedy'] },
    ],
  },
]
